### ISSUE TITLE
[URGENT] Security issue

### ISSUE THREAD

**Issue by CLATechTeam** [sweeptic/fcc-advanced-node#1]
Recently seen sensitive information I m not supposed to see as a user. Do you do bug bounties?

This is urgent

**Comment by sweeptic** [comment]
i see git ignore not working for some reason. Thank you for the warning.
corrected

Attila

Colton Adamski ***@***.***> ezt írta (időpont: 2021. máj. 4.,
K, 12:17):

**Comment by sweeptic** [comment]
fixed
